### ISSUE TITLE
Uso de um contexto

### ISSUE THREAD

**Issue by samuelcomputacao** [lucasmedeiros/game-slot#20]
Teu projeto ta bem bacana e aparentemente não tem muita coisa pra fazer. Eu dei uma olhada nos arquivos e não encontrei uso de contexto para propagação de estados dentro do teu sistema. É importante ter essa parte, pois ela é uma das entregas esperadas.

**Comment by lucasmedeiros** [comment]
Opa, tudo bem? Desculpa só ter visto hoje tua issue, mas o contexto usado foi o do Redux. Tinha falado com o professor e foi permitido! Muito obrigado 😄
