### ISSUE TITLE
[BACK] Reescrever criação de listas

### ISSUE THREAD

**Issue by lucasmedeiros** [lucasmedeiros/game-slot#54]
### Pré-requisitos

- #69 

### Descrição

Atualizar criação de listas por usuário a partir de informações de usuário obtidas pelo Auth0. Criar modelo que representará a relação entre um usuário e suas listas.

**Comment by jadsonluan** [comment]
Essa task já está completa devido a uma mudança na arquitetura da API não será mais necessário realizá-la
