### ISSUE TITLE
Improve your README.md

### ISSUE THREAD

**Issue by matheusgr** [lucasmedeiros/game-slot#8]
Please describe in your readme:

- [x] Technologies utilized
- [x] APIs that you are using
- [x] how to execute your application

**Comment by lucasmedeiros** [comment]
Thanks for suggesting this :smile:

Now this project and [its API](https://github.com/lucasmedeiros/game-slot-api) have a README, so I'm closing this issue. There's still work to be done on both of them, but now both explain how to run the project at this point.
